name: PGE Trivy

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    uses: pgepi/security-ci/.github/workflows/trivy.yml@847c1a7431b722ca0bb35ac7232e4d33bfdf9e59
    secrets: inherit