name: PGE Trivy

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    uses: pgepi/security-ci/.github/workflows/trivy.yml@48d85b96edcf340024a8ef29388ef78753319495
    secrets: inherit