name: PGE Trivy

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    uses: pgepi/security-ci/.github/workflows/trivy.yml@a647d39bcd72ff4378958358f30970b4f0565364
    secrets: inherit